CREATE TABLE PACIENTES (
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    PR_APELLIDO VARCHAR(30) NOT NULL,
    SG_APELLIDO VARCHAR(30) NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    NOTAS_CLINICAS TEXT NULL,
    CONSTRAINT PK_PACIENTES PRIMARY KEY (DNI)
);

CREATE TABLE SALAS (
    ID INT NOT NULL AUTO_INCREMENT, -- Añadido AUTO_INCREMENT
    NOMBRE_SALA VARCHAR(30) NOT NULL,
    CONSTRAINT PK_SALAS PRIMARY KEY (ID)
);

CREATE TABLE PROFESIONALES (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    ESPECIALIDAD VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PROFESIONALES PRIMARY KEY (ID)
);

CREATE TABLE CITAS (
    ID INT NOT NULL AUTO_INCREMENT,
    DNI_PACIENTE VARCHAR(9) NOT NULL,
    ID_PROFESIONAL INT NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    ID_SALA INT NOT NULL,
    DURACION INT NOT NULL,
    OBSERVACIONES TEXT NULL,
    CONSTRAINT PK_CITAS PRIMARY KEY (ID),
    CONSTRAINT FK_CITAS_PACIENTES FOREIGN KEY (DNI_PACIENTE) REFERENCES PACIENTES(DNI),
    CONSTRAINT FK_CITAS_SALAS FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID),
    CONSTRAINT FK_CITAS_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONALES(ID)
);
